// Flattened locations array from previous step
const locationsdata= [
  { city: 'Hyderabad', point: 'SR Nagar' },
  { city: 'Hyderabad', point: 'Banjara Hills' },
  { city: 'Hyderabad', point: 'Hitech City' },
  { city: 'Hyderabad', point: 'Madhapur' },
  { city: 'Hyderabad', point: 'Ameerpet' },
  { city: 'Bangalore', point: 'Koramangala' },
  { city: 'Bangalore', point: 'Whitefield' },
  { city: 'Bangalore', point: 'Indiranagar' },
  { city: 'Bangalore', point: 'MG Road' },
  { city: 'Bangalore', point: 'Jayanagar' },
  { city: 'Chennai', point: 'T Nagar' },
  { city: 'Chennai', point: 'Adyar' },
  { city: 'Chennai', point: 'Mount Road' },
  { city: 'Chennai', point: 'Besant Nagar' },
  { city: 'Chennai', point: 'Egmore' },
  { city: 'Goa', point: 'Panaji' },
  { city: 'Goa', point: 'Vasco da Gama' },
  { city: 'Goa', point: 'Calangute' },
  { city: 'Goa', point: 'Baga' },
  { city: 'Goa', point: 'Margao' },
  { city: 'Vijayawada', point: 'MG Road' },
  { city: 'Vijayawada', point: 'Rajendra Nagar' },
  { city: 'Vijayawada', point: 'Akkireddypalem' },
  { city: 'Vijayawada', point: 'Vidhyadharapuram' },
  { city: 'Vijayawada', point: 'Labbipet' },
  { city: 'Nellore', point: 'Ranganayakulapet' },
  { city: 'Nellore', point: 'Anandbagh' },
  { city: 'Nellore', point: 'Reddypalem' },
  { city: 'Nellore', point: 'Akkampet' },
  { city: 'Nellore', point: 'Sree Nagar' },
  { city: 'Jaipur', point: 'C-Scheme' },
  { city: 'Jaipur', point: 'Malviya Nagar' },
  { city: 'Jaipur', point: 'Vaishali Nagar' },
  { city: 'Jaipur', point: 'Jagatpura' },
  { city: 'Jaipur', point: 'Jhotwara' },
  { city: 'Mangalore', point: 'Balmatta' },
  { city: 'Mangalore', point: 'Kottara Chowki' },
  { city: 'Mangalore', point: 'Madhava Nagar' },
  { city: 'Mangalore', point: 'Bunder' },
  { city: 'Mangalore', point: 'PVS' },
  { city: 'Visakhapatnam', point: 'Benz Circle' },
  { city: 'Visakhapatnam', point: 'Jagadamba' },
  { city: 'Visakhapatnam', point: 'Dabagardens' },
  { city: 'Visakhapatnam', point: 'Kommadi' },
  { city: 'Visakhapatnam', point: 'Madhurawada' },
  { city: 'Delhi', point: 'Connaught Place' },
  { city: 'Delhi', point: 'Khan Market' },
  { city: 'Delhi', point: 'Karol Bagh' },
  { city: 'Delhi', point: 'Saket' },
  { city: 'Delhi', point: 'Vasant Kunj' },
  { city: 'Indore', point: 'MG Road' },
  { city: 'Indore', point: 'Rajwada' },
  { city: 'Indore', point: 'Vijay Nagar' },
  { city: 'Indore', point: 'Lal Baag' },
  { city: 'Indore', point: 'Rau' },
  { city: 'Kolkata', point: 'Park Street' },
  { city: 'Kolkata', point: 'Salt Lake' },
  { city: 'Kolkata', point: 'Howrah' },
  { city: 'Kolkata', point: 'Kolkata Airport' },
  { city: 'Kolkata', point: 'Dumdum' },
];

//const uniqueCities = [...new Set(L.map(location => location.city))];

const busdata = [
  {0: [
    {
      name: 'Shyamoli Paribahan',
      rating: 4.4,
      type: 'AC Sleeper',
      starttime: '17:00',
      endtime: '04:30',
      price: 1069,
      available: 16,
    },
    {
      name: 'LVP Travels',
      rating: 4.3,
      type: 'AC Sleeper (2+1)',
      starttime: '20:45',
      endtime: '07:00',
      price: 980,
      available: 10,
    },
    {
      name: 'Green Line',
      rating: 4.5,
      type: 'Non-AC Seater',
      starttime: '15:30',
      endtime: '23:30',
      price: 850,
      available: 20,
    },
    {
      name: 'Dolonchapa Paribahan',
      rating: 4.2,
      type: 'AC Sleeper (2+2)',
      starttime: '18:00',
      endtime: '05:00',
      price: 1120,
      available: 12,
    },
    {
      name: 'Hanif Paribahan',
      rating: 4.0,
      type: 'AC Seater',
      starttime: '19:30',
      endtime: '06:00',
      price: 950,
      available: 8,
    }
  ]},
  {1: [
    {
      name: 'Soudia Paribahan',
      rating: 4.1,
      type: 'AC Sleeper (2+1)',
      starttime: '21:00',
      endtime: '06:30',
      price: 1020,
      available: 14,
    },
    {
      name: 'Eagle Paribahan',
      rating: 4.3,
      type: 'Non-AC Seater',
      starttime: '20:30',
      endtime: '05:30',
      price: 850,
      available: 18,
    },
    {
      name: 'Shahjalal Express',
      rating: 4.6,
      type: 'AC Seater',
      starttime: '23:15',
      endtime: '08:00',
      price: 970,
      available: 10,
    },
    {
      name: 'Sakura Travels',
      rating: 4.2,
      type: 'AC Sleeper (2+2)',
      starttime: '22:00',
      endtime: '07:15',
      price: 1000,
      available: 12,
    },
    {
      name: 'Purbani Express',
      rating: 4.0,
      type: 'Non-AC Seater',
      starttime: '19:00',
      endtime: '04:00',
      price: 800,
      available: 22,
    }
  ]},
  {2: [
    {
      name: 'Bengal Paribahan',
      rating: 4.7,
      type: 'AC Sleeper',
      starttime: '18:45',
      endtime: '05:30',
      price: 1200,
      available: 15,
    },
    {
      name: 'Saint Martin Express',
      rating: 4.4,
      type: 'AC Seater',
      starttime: '20:00',
      endtime: '06:00',
      price: 900,
      available: 20,
    },
    {
      name: 'Khaled Travels',
      rating: 4.5,
      type: 'Non-AC Seater',
      starttime: '21:30',
      endtime: '07:30',
      price: 850,
      available: 18,
    },
    {
      name: 'Royal Bengal',
      rating: 4.2,
      type: 'AC Sleeper (2+2)',
      starttime: '23:00',
      endtime: '09:00',
      price: 1150,
      available: 14,
    },
    {
      name: 'Silk Route Express',
      rating: 4.3,
      type: 'AC Sleeper',
      starttime: '22:00',
      endtime: '08:30',
      price: 1100,
      available: 16,
    }
  ]},
  {3: [
    {
      name: 'Pride Travels',
      rating: 4.0,
      type: 'AC Sleeper',
      starttime: '18:00',
      endtime: '06:00',
      price: 1000,
      available: 20,
    },
    {
      name: 'Uttara Paribahan',
      rating: 4.3,
      type: 'AC Seater',
      starttime: '17:30',
      endtime: '05:30',
      price: 900,
      available: 12,
    },
    {
      name: 'Dhaka Express',
      rating: 4.5,
      type: 'Non-AC Seater',
      starttime: '19:30',
      endtime: '08:00',
      price: 850,
      available: 22,
    },
    {
      name: 'Jamuna Paribahan',
      rating: 4.2,
      type: 'AC Sleeper (2+2)',
      starttime: '20:00',
      endtime: '07:00',
      price: 1050,
      available: 18,
    },
    {
      name: 'Sonar Bangla Express',
      rating: 4.4,
      type: 'AC Seater',
      starttime: '22:15',
      endtime: '08:15',
      price: 950,
      available: 16,
    }
  ]},
  {4: [
    {
      name: 'Green Line Express',
      rating: 4.6,
      type: 'AC Sleeper',
      starttime: '16:00',
      endtime: '03:00',
      price: 1200,
      available: 14,
    },
    {
      name: 'Dreamline Travels',
      rating: 4.4,
      type: 'Non-AC Seater',
      starttime: '17:15',
      endtime: '06:15',
      price: 850,
      available: 20,
    },
    {
      name: 'Comfort Travels',
      rating: 4.5,
      type: 'AC Seater',
      starttime: '18:30',
      endtime: '07:00',
      price: 990,
      available: 12,
    },
    {
      name: 'Shamoli Paribahan (Luxury)',
      rating: 4.7,
      type: 'AC Sleeper (2+1)',
      starttime: '20:00',
      endtime: '07:30',
      price: 1200,
      available: 10,
    },
    {
      name: 'Farhana Paribahan',
      rating: 4.3,
      type: 'Non-AC Seater',
      starttime: '21:00',
      endtime: '06:00',
      price: 800,
      available: 22,
    }
  ]},
  {5: [
    {
      name: 'Moonlight Express',
      rating: 4.2,
      type: 'AC Sleeper',
      starttime: '17:45',
      endtime: '04:00',
      price: 1100,
      available: 15,
    },
    {
      name: 'Skyline Travels',
      rating: 4.3,
      type: 'AC Seater',
      starttime: '19:30',
      endtime: '05:30',
      price: 950,
      available: 18,
    },
    {
      name: 'Shahjalal Travels',
      rating: 4.4,
      type: 'Non-AC Seater',
      starttime: '20:30',
      endtime: '06:30',
      price: 850,
      available: 20,
    },
    {
      name: 'Madhumati Paribahan',
      rating: 4.5,
      type: 'AC Sleeper (2+2)',
      starttime: '22:00',
      endtime: '08:00',
      price: 1070,
      available: 12,
    },
    {
      name: 'Sundarban Express',
      rating: 4.1,
      type: 'AC Sleeper',
      starttime: '21:00',
      endtime: '06:30',
      price: 990,
      available: 16,
    }
  ]},
  {6: [
    {
      name: 'Princess Travels',
      rating: 4.2,
      type: 'AC Seater',
      starttime: '16:30',
      endtime: '04:00',
      price: 950,
      available: 18,
    },
    {
      name: 'Oasis Paribahan',
      rating: 4.0,
      type: 'Non-AC Seater',
      starttime: '17:15',
      endtime: '06:15',
      price: 800,
      available: 18,
    }
  ]},
  {7:[
    {
      name: 'Shyamoli Paribahan',
      rating: 4.4,
      type: 'AC Sleeper',
      starttime: '17:00',
      endtime: '04:30',
      price: 1069,
      available: 16,
    },
    {
      name: 'LVP Travels',
      rating: 4.3,
      type: 'AC Sleeper (2+1)',
      starttime: '20:45',
      endtime: '07:00',
      price: 980,
      available: 10,
    },
    {
      name: 'Green Line',
      rating: 4.5,
      type: 'Non-AC Seater',
      starttime: '15:30',
      endtime: '23:30',
      price: 850,
      available: 20,
    },
    {
      name: 'Dolonchapa Paribahan',
      rating: 4.2,
      type: 'AC Sleeper (2+2)',
      starttime: '18:00',
      endtime: '05:00',
      price: 1120,
      available: 12,
    },
    {
      name: 'Hanif Paribahan',
      rating: 4.0,
      type: 'AC Seater',
      starttime: '19:30',
      endtime: '06:00',
      price: 950,
      available: 8,
    }
  ]},
  {8: [
    {
      name: 'Soudia Paribahan',
      rating: 4.1,
      type: 'AC Sleeper (2+1)',
      starttime: '21:00',
      endtime: '06:30',
      price: 1020,
      available: 14,
    },
    {
      name: 'Eagle Paribahan',
      rating: 4.3,
      type: 'Non-AC Seater',
      starttime: '20:30',
      endtime: '05:30',
      price: 850,
      available: 18,
    },
    {
      name: 'Shahjalal Express',
      rating: 4.6,
      type: 'AC Seater',
      starttime: '23:15',
      endtime: '08:00',
      price: 970,
      available: 10,
    },
    {
      name: 'Sakura Travels',
      rating: 4.2,
      type: 'AC Sleeper (2+2)',
      starttime: '22:00',
      endtime: '07:15',
      price: 1000,
      available: 12,
    },
    {
      name: 'Purbani Express',
      rating: 4.0,
      type: 'Non-AC Seater',
      starttime: '19:00',
      endtime: '04:00',
      price: 800,
      available: 22,
    }
  ]},
  {9: [
    {
      name: 'Bengal Paribahan',
      rating: 4.7,
      type: 'AC Sleeper',
      starttime: '18:45',
      endtime: '05:30',
      price: 1200,
      available: 15,
    },
    {
      name: 'Saint Martin Express',
      rating: 4.4,
      type: 'AC Seater',
      starttime: '20:00',
      endtime: '06:00',
      price: 900,
      available: 20,
    },
    {
      name: 'Khaled Travels',
      rating: 4.5,
      type: 'Non-AC Seater',
      starttime: '21:30',
      endtime: '07:30',
      price: 850,
      available: 18,
    },
    {
      name: 'Royal Bengal',
      rating: 4.2,
      type: 'AC Sleeper (2+2)',
      starttime: '23:00',
      endtime: '09:00',
      price: 1150,
      available: 14,
    },
    {
      name: 'Silk Route Express',
      rating: 4.3,
      type: 'AC Sleeper',
      starttime: '22:00',
      endtime: '08:30',
      price: 1100,
      available: 16,
    }
  ]},
];

export {locationsdata,busdata};
